[package]
distribution = "2201.13.0"
org = "ballerinax"
name = "sap.commerce.webservices"
version = "0.1.0"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = []
# icon = "icon.png" # TODO: update icon.png
repository = "https://github.com/ballerina-platform/module-ballerinax-sap.commerce.webservices"

[build-options]
observabilityIncluded = true

[platform.java21]
graalvmCompatible = true
